### ISSUE TITLE
Neither Heroku, nor DigitalOcean works 

### ISSUE THREAD

**Issue by nikolay** [monty5811/apostello#38]
The app sets up on Heroku, but then you can't do anything as you keep getting 403 errors on testing email, SMS, and admin creation.

**Comment by monty5811** [comment]
That's odd. Someone else got heroku up and running a couple of days ago.

I'll set up a new instance to see if I broke anything.

**Comment by nikolay** [comment]
Thanks! It seems that gunicorn is not letting any traffic in from the OpsBeat traces.

**Comment by monty5811** [comment]
Looks like it was a CSRF error on the page. I have tested a deployment on Heroku with the fix and it is working fine now.

Let me know if you hit any other issues.
