### ISSUE TITLE
Unknown Person in history

### ISSUE THREAD

**Issue by nikolay** [monty5811/apostello#41]
Once you update the name of a person, in history, it still shows the old name, in my case, "Unknown Person".

**Comment by monty5811** [comment]
Oh, thanks, I'll change it so we can update the back log when a contact is saved. This will be in the next release.

You can run `./manage.py update_sms_name_fields` from the command line to do this manually at the minute. It will do it for every contact.

How you run the command will depend on how you have deployed apostello
