### ISSUE TITLE
Multi-tenancy

### ISSUE THREAD

**Issue by nikolay** [monty5811/apostello#42]
I'm doing a free service to a couple of churches that use the same phone number. I think it would be nice to have a message in the form of `join <group>`, which might require approval.

A hack would be to auto treat groups as join keywords.

Another way would be to support multiple phone numbers are assign them to organizations. The thing is that it is possible (in the case of Orthodox churches, at least) that one person goes to more than one church.

**Comment by nikolay** [comment]
Maybe to avoid redundant moderation, groups can be open or closed, and then everybody can join a group unless it's not public, which could then be added to only via the admin UI.

**Comment by monty5811** [comment]
Not quite sure I understand. You seem to be talking about 2 different options?

### Option 1

You want to let people join a group by SMS? And then you want to have each group be responsible for a different church?

Though each church would still be sharing the keywords with this setup.

Feel free to send a PR if you want to implement this feature.

### Option 2

You want to receive and send messages from multiple phone numbers? But share contacts across these phone numbers? I think this is probably beyond the scope of the project and would make apostello significantly more complicated...

Am I understanding you correctly?

If it were me, I would probably just setup multiple instances of apostello...

**Comment by nikolay** [comment]
In option 1, if there's filtering by groups, then sharing keywords is not really a problem. For example, there can be a keyword for helping with Easter lunch, then it will be the same across churches anyway, but you bring a valid point as then it won't be clear to which lunch they are responding to.

Separate instances is definitely fine, but increases the costs - hosting, dedicated numbers, etc.

Anyway, I will think more about refining the proposal.

**Comment by monty5811** [comment]
You could run two instances on one server to keep hosting costs down. You would need to run both of them and then reverse proxy them. But you would still have the increased cost from multiple numbers...

**Comment by monty5811** [comment]
I'm going to close this for now. Feel free to re-open it or another issue in the future.
