### ISSUE TITLE
Integrate with Mailtrain

### ISSUE THREAD

**Issue by nikolay** [monty5811/apostello#43]
In addition to #8, it would be nice to integrate also with [Mailtrain](https://mailtrain.org/).

**Comment by nikolay** [comment]
https://github.com/andris9/mailtrain

**Comment by monty5811** [comment]
What do you envisage this integration looking like? Do you want apostello emails to go through mailtrain or something else?

It looks like you need to bring your own smtp server (or service like mailgun) to use mailtrain. Could you not just use the same smtp server with apostello?

Also, the list of [cons](https://github.com/andris9/mailtrain#cons), makes me wary of spending any time on an integration.

**Comment by nikolay** [comment]
@monty5811 I think Mailtrain will survive as pretty much there are no other open-source alternatives. I think, if integration is made, it should be done via a plugin so that Apostello can be integrated with Mailchimp, etc. The idea would be to abstract to Address Book so that it can be mounted from external sources as well, and possibly just cached locally for performance. So, this is not so much about using Mailtrain to send emails.

For example, this is how I envision the perfect system:

1. People sign up in one place and elect how to get notified for different types of message - email, text message, maybe other means in the future, too.
2. When I message needs to be relayed to a group of people, it honors their communication preference.

**Comment by monty5811** [comment]
That would be cool.

I think the best way to do it would be to expose the apostello contacts list via an api. What do you think?

This should be fairly easy to do, too as all the groundwork is already there - the tables are all loaded via API views that we just need to expose so other services could access them.

**Comment by monty5811** [comment]
The next release will allow access to the API so I am going to close this issue.

Docs: https://apostello.readthedocs.io/en/latest/api.html
