### ISSUE TITLE
Make size of content fields on sending forms a function of the max message limit

### ISSUE THREAD

**Issue by nikolay** [monty5811/apostello#46]
[Twilio supports large messages up t0 1600 characters](https://www.twilio.com/help/faq/sms/does-twilio-support-concatenated-sms-messages-or-messages-over-160-characters), which it breaks transparently into 160-character ones. I've been broadcasting large texts for months and I wanted to switch to Apostello tonight but got hit with the 150 character limit. Please, add the option to have a textarea with 1600-character limit.

**Comment by monty5811** [comment]
You can alter the limit in `Tools --> Site Configuration`. So you can send longer messages today.

The text box will however remain the same size. 

I can change it so that the number of rows in the text area is a function of the maximum message length.

**Comment by nikolay** [comment]
@monty5811 When I tried sending a longer message and although the limit by default is 160, Apostello complained that the message is longer than 150. So, why 150 and not 160?

**Comment by monty5811** [comment]
It is to handle the `%name%` substitution functionality.

**Comment by monty5811** [comment]
I could make it more sophisticated so that limit only kicks in if a name is actually being substituted in
