### ISSUE TITLE
Add ability to perform set operations on groups for sending messages

### ISSUE THREAD

**Issue by AustinBratcher** [monty5811/apostello#53]
This idea stemmed from the fact that there isn't a default way to remove someone from the list. The goal would be to have the ability to send to some subset of a group. i.e. If I have group A and group B, but I only want to send to members of A that are not in B, I should be able to specify that I want to send to A - B. 

Having the ability to preform set operations such as union, intersection, complement, difference, and combinations thereof could add some powerful functionality to Apostello.

**Comment by monty5811** [comment]
This is now in the demo instance at apostello-demo@herokuapp.com 

Login as `test@example.com` with pass `apostello`, thencClick on `Tools -> Compose Group` to try it.

Any feedback very welcome.

**Comment by monty5811** [comment]
Demo:
![apostello-group-composer](https://cloud.githubusercontent.com/assets/5426677/20194514/7d65ff26-a78a-11e6-925f-358bfd987a2f.gif)

**Comment by monty5811** [comment]
Relased in [v1.14.0](https://github.com/monty5811/apostello/releases/tag/v1.14.0)
