### ISSUE TITLE
Built in URL Shortener

### ISSUE THREAD

**Issue by AustinBratcher** [monty5811/apostello#67]
As each message has a character limit, it would be nice to have real time url shortening with a custom domain. In theory, as I am typing a url, Apostello would be able to parse said url and replace the text with a shortened URL. Twilio does have some kind of url shortening service, but having it built in on the front end to see how it affects the cost of the message would be very handy.

**Comment by monty5811** [comment]
As I see it, there are two ways to do this:

1. Use something like goo.gl to do the shortening
2. Do the shortening in apostello

## Using an external service

Pros:

* Fairly easy, just have to hook up api
* ???

Cons:

* Will leak urls to a third party
* May require an api key
* ???

## Doing in apostello

Pros:

* Does not leak urls
* Should be easy to implement with an existing django app

Cons:

* Requires apostello to be behind a reasonably short url or the generated "short url" won't save many characters.

@AustinBratcher - which did you have in mind?

**Comment by monty5811** [comment]
Closing this through lack of interest.

Please feel free to bring it up again.
