### ISSUE TITLE
new install issue

### ISSUE THREAD

**Issue by losto** [monty5811/apostello#84]
It looks like the new firebase setup broke at least the digitalocean install...

from these instructions: https://apostello.readthedocs.io/en/latest/deploy_do.html

when doing this step:
./home/apostello/apostello-install/scripts/ansible_install.sh

I get this error:
fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'cm_server_key' is undefined"}

I then attempted to follow the ansible instructions and I found a config file that had those values set in /home/apostello/apostello-install/ansible/env_vars/example.yml which appears to have resolved the issue

**Comment by losto** [comment]
I thought I had it after the above, but still having an issue with default digital ocean install:

![screen shot 2017-09-12 at 9 21 04 pm](https://user-images.githubusercontent.com/9090670/30359535-582edef0-9800-11e7-9dc3-ecb5085e2f11.png)
![screen shot 2017-09-12 at 9 21 10 pm](https://user-images.githubusercontent.com/9090670/30359537-5b1d35c6-9800-11e7-9320-b0d2d220ed89.png)
![screen shot 2017-09-12 at 9 21 14 pm](https://user-images.githubusercontent.com/9090670/30359540-5cd35d78-9800-11e7-9529-5aff2db8fa5b.png)

**Comment by losto** [comment]
BTW, this is all with V2.5.1

![screen shot 2017-09-12 at 9 22 43 pm](https://user-images.githubusercontent.com/9090670/30359609-ca0ef17c-9800-11e7-8b30-49ee1da0cc9f.png)

**Comment by losto** [comment]
Just for kicks I also fired up a Herokuapp.  Installed and got to first_run without any issues, however still having show stopping issue on the csrftoken, identical error to above.

**Comment by monty5811** [comment]
Thanks for the detailed report! It will be a few days before I can get round to fixing it...

**Comment by monty5811** [comment]
Thanks again @losto - the error messages were very helpful.

The digital ocean install should be fixed now (by monty5811/apostello-do-install@3e6bca1208da8449ce27bb24a9d5e582c35ba90f). And the CSRF issue should also be resolved for both deployment methods in v2.5.3

I have just tested both methods and they are working. Please let me know if you run into any other issues. And thanks again for the detailed bug report.
