### ISSUE TITLE
Apostello & Azure

### ISSUE THREAD

**Issue by ourchurchny** [monty5811/apostello#88]
Is there a way to deploy Apostello using Microsoft Azure?

**Comment by monty5811** [comment]
I can't see why not. 

You should be able to provision a VM and then follow the instructions here: http://apostello.readthedocs.io/en/latest/deploy_ansible.html to get everything setup.

**Comment by ourchurchny** [comment]
Thanks for getting back so quickly!  I am completely new to all of this.  I am not sure exactly where I would put the code from that site on a VM.  When you say "provision" does this mean set one up with windows server?

**Comment by monty5811** [comment]
No problem.

"Provision" - yeah, that means set up a new VM. However, apostello has only been tested on Linux, it should, in theory, be able to run on Windows, but it would take a lot of configuring to do so.

I recommend, if you are new to all of this, either using Heroku or Digital Ocean to deploy apostello. Heroku will manage pretty much everything for you and it will be free to try (and should remain free unless you send a huge number of SMS) - there is no VM to manage, it is all done for you. DigitalOcean will be a traditional VM that you will need to manage and setup a domain for.

Heroku deployment: http://apostello.readthedocs.io/en/latest/deploy_heroku.html
Digital Ocean deployment: http://apostello.readthedocs.io/en/latest/deploy_do.html

If you have more questions, feel free to jump into our chat: http://chat.church.io/ to get more help.

**Comment by monty5811** [comment]
Closing this, feel free to reopen.
