### ISSUE TITLE
Support for Ubuntu 18.04

### ISSUE THREAD

**Issue by norrist** [monty5811/apostello#90]
I have done some testing with the beta release of Ubuntu 18.04 and was able to the ansible-playbook working with these changes:

```
diff --git a/ansible/roles/base/tasks/main.yml b/ansible/roles/base/tasks/main.yml
index 68c0d3b..9fc2494 100644
--- a/ansible/roles/base/tasks/main.yml
+++ b/ansible/roles/base/tasks/main.yml
@@ -41,7 +41,8 @@
     - sudo
     - python3-venv
   tags: packages
-  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'
+  when: (ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04') or
+        (ansible_distribution == 'Ubuntu' and ansible_distribution_version == '18.04')

 - name: Start supervisor
   service: name=supervisor state=started enabled=yes
diff --git a/ansible/roles/db/tasks/main.yml b/ansible/roles/db/tasks/main.yml
index 0f98a57..5e4148f 100644
--- a/ansible/roles/db/tasks/main.yml
+++ b/ansible/roles/db/tasks/main.yml
@@ -29,6 +29,7 @@
                    password={{ db_password }}
                    priv=ALL
                    state=present
+                   encrypted=yes
```

There may be a better way to include '18.04' when installing packages, but the package names for 16.04 and 18.04 are the same.

Also, I am not sure of the impact of adding "encrypted=yes" to the task that creates the postgresql user, but the modification was necessary  to add it to get the playbook to run.

**Comment by monty5811** [comment]
Thank you very much.

I'll aim to merge this before 18.04 is out of beta. And I'll add 18.04 to the deployment tests.

Thanks again!

**Comment by monty5811** [comment]
Ubuntu 18.04 is now fully supported.
Support for previous versions have been dropped.
