### ISSUE TITLE
Digital Ocean Droplet Installer - Errors After Build Script

### ISSUE THREAD

**Issue by jandrusk** [monty5811/apostello#91]
I did follow the documentation, but I'm getting build errors at the end of the DO Droplet installer process. I've tried it twice and the web server never ends up starting, I'm guessing due to the build errors. Attaching the output from the tail log trace. 

![apostello_install_error](https://user-images.githubusercontent.com/1035829/37941983-f05af092-313e-11e8-93aa-558caa6d15a0.png)

**Comment by monty5811** [comment]
Hi, 
Thanks for the detailed bug report!

I think I have just fixed this (04b2652) - the `ansible/env_vars/example.yml` file had a small error in it.

The lines 

```
rollbar_access_token:
rollbar_access_token_client:
```

Should be 
```
rollbar_access_token: ''
rollbar_access_token_client: ''
```

**Comment by jandrusk** [comment]
Thanks. Should this work if I build a new Digital Ocean droplet from the installer?

**Comment by jandrusk** [comment]
That did it! Thanks for all the help.
